function update(dt){if(mode==='launch'){controls(dt,.8);let g=9.81*Math.max(.08,1-ship.alt/150000);thrust(dt);ship.vy-=g*dt;let air=Math.max(0,1-ship.alt/62000),drag=air*.00045*(1-Math.min(.7,stats().wing*.08));ship.vx-=ship.vx*Math.abs(ship.vx)*drag*dt;ship.vy-=ship.vy*Math.abs(ship.vy)*drag*dt;ship.x+=ship.vx*dt;ship.y+=ship.vy*dt;ship.alt=Math.max(0,ship.y);if(ship.alt<=0&&ship.vy<-18)return crash('The rocket hit the launch site too fast.');if(ship.alt>=70000&&Math.abs(ship.vx)>=1650){mode='orbit';ship.th=0;ship.vy=0;banner('<b>Orbit achieved:</b> choose a destination below.');log('<b>Stable orbit achieved.</b>');phaseUI()}else if(ship.alt>25000&&Math.abs(ship.vx)<500)banner('<b>Tip:</b> hold the right rotate button to build horizontal speed.')}else if(mode==='orbit'){controls(dt,.3);ship.a+=.035*dt;ship.alt=90000+Math.sin(performance.now()/1800)*1200;ship.vx=1750;ship.vy=0}else if(mode==='transfer'){progress+=dt/duration;ship.a+=.06*dt;if(progress>=1)descend()}else if(mode==='landing'){let p=ship.target;controls(dt,1.1);thrust(dt,.75);ship.vy-=p.g*dt;let air=p.id==='viridia'?.0042:p.id==='ares'?.0007:.00015;ship.vx-=ship.vx*Math.abs(ship.vx)*air*dt;ship.vy-=ship.vy*Math.abs(ship.vy)*air*dt;ship.x+=ship.vx*dt;ship.y+=ship.vy*dt;ship.alt=Math.max(0,ship.y);if(ship.y<=0){ship.y=0;let upright=Math.abs(ship.a)<(ship.legs>=2?.38:.22),hs=Math.abs(ship.vx)<(ship.legs>=2?12:6),vs=Math.abs(ship.vy)<=p.safe+Math.min(3,ship.legs);if(upright&&hs&&vs)landed();else crash(!vs?`Touchdown speed was ${Math.abs(ship.vy).toFixed(1)} m/s.`:!upright?'The craft struck at an unsafe angle.':'Horizontal drift tipped the craft over.')}}parts.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});parts=parts.filter(p=>p.life>0);hud()}
function hud(){let fp=ship.maxFuel?Math.max(0,ship.fuel/ship.maxFuel)*100:0;$('fuel').textContent=`${Math.max(0,Math.round(ship.fuel))} / ${Math.round(ship.maxFuel)}`;$('fuelbar').style.width=fp+'%';$('hull').textContent=Math.max(0,Math.round(ship.hull))+'%';$('hullbar').style.width=Math.max(0,ship.hull)+'%';$('alt').textContent=ship.alt>1000?(ship.alt/1000).toFixed(1)+' km':Math.round(ship.alt)+' m';$('vy').textContent=Math.round(ship.vy)+' m/s';$('vx').textContent=Math.round(Math.abs(ship.vx))+' m/s';$('throttle').textContent=Math.round(ship.th*100)+'%';saveUI()}
function resizeFlight(){let r=cv.getBoundingClientRect();if(!r.width||!r.height)return;let d=Math.min(devicePixelRatio||1,2);cv.width=Math.round(r.width*d);cv.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);cv.w=r.width;cv.h=r.height;stars=Array.from({length:Math.floor(r.width*r.height/4200)},()=>({x:Math.random()*r.width,y:Math.random()*r.height,r:Math.random()*1.4+.2,a:Math.random()*.7+.2}))}
function bg(a,b){let g=ctx.createLinearGradient(0,0,0,cv.h);g.addColorStop(0,a);g.addColorStop(1,b);ctx.fillStyle=g;ctx.fillRect(0,0,cv.w,cv.h)}
function star(alpha=1,drift=0){ctx.fillStyle='#e4f8ff';stars.forEach(s=>{ctx.globalAlpha=s.a*alpha;ctx.beginPath();ctx.arc((s.x+drift+cv.w)%cv.w,s.y,s.r,0,7);ctx.fill()});ctx.globalAlpha=1}
function rocket(x,y,s=1,a=ship.a){let cells=[];grid.forEach((row,r)=>row.forEach((k,c)=>k&&cells.push({k,r,c})));if(!cells.length)return;let minR=Math.min(...cells.map(p=>p.r)),maxR=Math.max(...cells.map(p=>p.r)),minC=Math.min(...cells.map(p=>p.c)),maxC=Math.max(...cells.map(p=>p.c)),u=17*s,w=(maxC-minC+1)*u,h=(maxR-minR+1)*u;ctx.save();ctx.translate(x,y);ctx.rotate(a);cells.forEach(p=>moduleDraw(ctx,p.k,(p.c-minC+.5)*u-w/2,(p.r-minR+.5)*u-h/2,u*.88));ctx.restore()}
function particlesAt(x,y,scale){parts.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.col;ctx.beginPath();ctx.arc(x+(p.x-ship.x)*scale,y-(p.y-ship.y)*scale,p.r,0,7);ctx.fill()});ctx.globalAlpha=1}
function launchDraw(){bg('#071221','#4b7288');let q=Math.min(1,ship.alt/80000);if(q>.5){bg('#020611','#07101d');star(Math.max(0,(ship.alt-15000)/50000))}let gy=cv.h-65+Math.min(cv.h*.72,ship.alt/220);if(gy<cv.h+30){ctx.fillStyle='#273d45';ctx.fillRect(0,gy,cv.w,cv.h-gy)}let x=cv.w/2+Math.max(-cv.w*.28,Math.min(cv.w*.28,ship.x*.05)),y=cv.h*.64;particlesAt(x,y,.065);rocket(x,y,1.15)}
function orbitDraw(){bg('#02050e','#061326');star(1,performance.now()*.0015);let r=Math.max(230,cv.w*.75),x=cv.w/2,y=cv.h+r*.68,g=ctx.createRadialGradient(x-r*.3,y-r*.5,r*.1,x,y,r);g.addColorStop(0,'#72dbff');g.addColorStop(.55,'#1c6ba0');g.addColorStop(1,'#082642');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();let t=performance.now()/1500;rocket(cv.w/2+Math.cos(t)*70,cv.h*.38+Math.sin(t)*24,.9)}
function planet(x,y,r,col){let g=ctx.createRadialGradient(x-r*.3,y-r*.3,r*.1,x,y,r);g.addColorStop(0,'white');g.addColorStop(.1,col);g.addColorStop(1,'#07101d');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill()}
function transferDraw(){bg('#01040c','#071326');star(1,-performance.now()*.018);let p=Math.min(1,progress),sx=55+(cv.w-110)*p,sy=cv.h*.62-Math.sin(p*Math.PI)*cv.h*.3;ctx.strokeStyle='#65e4ff44';ctx.setLineDash([7,8]);ctx.beginPath();ctx.moveTo(45,cv.h*.62);ctx.quadraticCurveTo(cv.w/2,cv.h*.07,cv.w-55,cv.h*.62);ctx.stroke();ctx.setLineDash([]);planet(42,cv.h*.66,28,'#3184af');planet(cv.w-42,cv.h*.62,34,ship.target.col);rocket(sx,sy,.72,Math.PI/2)}
function landingDraw(){let p=ship.target||WORLDS[0];bg(p.sky,p.ground);star(p.id==='viridia'?.18:.75);let gy=cv.h-60;ctx.fillStyle=p.ground;ctx.beginPath();ctx.moveTo(0,gy);for(let x=0;x<=cv.w;x+=28)ctx.lineTo(x,gy+Math.sin(x*.025+p.dist)*8+Math.sin(x*.071)*4);ctx.lineTo(cv.w,cv.h);ctx.lineTo(0,cv.h);ctx.fill();let q=Math.max(.02,Math.min(1,ship.alt/12500)),y=gy-25-q*(cv.h-135),x=cv.w/2+Math.max(-cv.w*.32,Math.min(cv.w*.32,ship.x*.7));particlesAt(x,y,.72);rocket(x,y,1.1)}
function draw(){if(!cv.w)return;if(mode==='launch')launchDraw();else if(mode==='orbit')orbitDraw();else if(mode==='transfer')transferDraw();else landingDraw()}
function loop(now){let dt=Math.min(.033,Math.max(.001,(now-last)/1000));last=now;update(dt);draw();requestAnimationFrame(loop)}
addEventListener('resize',resizeFlight);addEventListener('orientationchange',()=>setTimeout(resizeFlight,150));requestAnimationFrame(loop);
