'use strict';
const $=id=>document.getElementById(id);
const buildCanvas=$('builderCanvas'),bctx=buildCanvas.getContext('2d');
const cv=$('game'),ctx=cv.getContext('2d');
const P={pod:{n:'Command Pod',i:'◆',m:3,f:0,t:0,c:350,col:'#c4e7f7'},tank:{n:'Fuel Tank',i:'▣',m:4,f:110,t:0,c:220,col:'#69cfe8'},engine:{n:'Vector Engine',i:'▼',m:4,f:0,t:145,c:460,col:'#a184ff'},boost:{n:'Solid Booster',i:'▮',m:6,f:65,t:230,c:390,col:'#ffb65f'},wing:{n:'Stability Fin',i:'◢',m:1.5,f:0,t:0,c:90,col:'#6ef0ae'},leg:{n:'Landing Leg',i:'⌁',m:1,f:0,t:0,c:110,col:'#f3d66f'}};
const WORLDS=[{id:'luna',n:'Luna',meta:'Low gravity · forgiving',col:'#aebed1',sky:'#07101e',ground:'#778494',g:2.4,dist:5,reward:900,safe:12},{id:'ares',n:'Ares',meta:'Thin air · rough terrain',col:'#d96d47',sky:'#2d1010',ground:'#8f3f2a',g:4.2,dist:8,reward:1500,safe:9},{id:'viridia',n:'Viridia',meta:'Dense air · strong gravity',col:'#5ec59a',sky:'#09262d',ground:'#2f7b66',g:7.1,dist:12,reward:2500,safe:7}];
let save;try{save={credits:3000,best:0,unlock:1,landings:0,...JSON.parse(localStorage.ofsave||'{}')}}catch{save={credits:3000,best:0,unlock:1,landings:0}}
const persist=()=>localStorage.ofsave=JSON.stringify(save);
let grid=Array.from({length:8},()=>Array(5).fill(null)),chosen='pod',world='luna',mode='build',stars=[],parts=[],logs=[],last=performance.now(),progress=0,duration=0,modal=false;
const key={left:false,right:false,up:false,down:false};
const ship={x:0,y:0,vx:0,vy:0,a:0,av:0,th:0,fuel:0,maxFuel:0,hull:100,mass:0,thrust:0,control:1,legs:0,target:null,alt:0};
function stats(){let s={mass:0,fuel:0,thrust:0,cost:0,pod:0,engine:0,boost:0,wing:0,leg:0};grid.flat().forEach(k=>{if(!k)return;let p=P[k];s.mass+=p.m;s.fuel+=p.f;s.thrust+=p.t;s.cost+=p.c;s[k]++});s.twr=s.mass?s.thrust/(s.mass*9.81):0;s.valid=s.pod>0&&(s.engine+s.boost)>0&&s.fuel>0&&s.twr>1.05;return s}
const fmt=n=>Math.round(n).toLocaleString();
function showScreen(name){$('buildScreen').classList.toggle('active',name==='build');$('flightScreen').classList.toggle('active',name==='flight');$('screenTitle').textContent=name==='build'?'Build your ship':'Fly your mission';window.scrollTo({top:0,behavior:'auto'});requestAnimationFrame(resizeFlight)}
function log(t){logs.unshift(t);logs=logs.slice(0,10);$('log').innerHTML=logs.map(x=>`<div class="line">${x}</div>`).join('')}
function banner(t){$('banner').innerHTML=t}
function saveUI(){$('credits').textContent=fmt(save.credits)}
function drawPartsUI(){$('parts').innerHTML='';Object.entries(P).forEach(([k,p])=>{let b=document.createElement('button');b.className='part'+(chosen===k?' on':'');b.innerHTML=`<span class="ico" style="color:${p.col}">${p.i}</span><span class="pn">${p.n}</span>`;b.onclick=()=>{if(mode==='build'){chosen=k;drawPartsUI()}};$('parts').appendChild(b)})}
function updateBuild(){let s=stats();$('mass').textContent=s.mass.toFixed(1)+' t';$('thrust').textContent=Math.round(s.thrust)+' kN';$('fuelm').textContent=Math.round(s.fuel)+' u';$('twr').textContent=s.twr.toFixed(2);$('rating').textContent=s.valid?(s.twr>2.4?'POWERFUL':s.twr>1.55?'BALANCED':'HEAVY'):'INCOMPLETE';$('rating').style.color=s.valid?'var(--good)':'var(--warn)';let c=[[s.pod>0,'Command pod installed'],[s.engine+s.boost>0,'Propulsion installed'],[s.fuel>0,'Fuel connected'],[s.twr>1.05,'TWR above 1.05'],[s.leg>=2,'Two legs recommended']];$('check').innerHTML=c.map(x=>`<li class="${x[0]?'ok':''}">${x[1]}</li>`).join('');$('launch').disabled=!s.valid||s.cost>save.credits;$('launch').textContent=s.cost>save.credits?`Need ${fmt(s.cost-save.credits)} credits`:`Launch mission · ◈ ${fmt(s.cost)}`;drawBuilder()}
function drawWorldUI(){$('planets').innerHTML='';WORLDS.forEach((p,i)=>{let b=document.createElement('button');b.className='planet'+(world===p.id?' on':'');b.disabled=i>=save.unlock;b.innerHTML=`<i class="orb" style="background:${p.col}"></i><span><span class="pname">${p.n}</span><span class="pmeta">${p.meta}</span></span><span class="tag">${i>=save.unlock?'LOCKED':p.dist+' AU'}</span>`;b.onclick=()=>{world=p.id;drawWorldUI()};$('planets').appendChild(b)})}
function starter(){grid=Array.from({length:8},()=>Array(5).fill(null));grid[1][2]='pod';grid[2][2]='tank';grid[3][2]='tank';grid[4][2]='engine';grid[3][1]=grid[3][3]='wing';grid[5][1]=grid[5][3]='leg';updateBuild();log('Starter blueprint loaded.')}
function phaseUI(){let n={build:'Assembly',launch:'Launch',orbit:'Orbit',transfer:'Transfer',landing:'Landing',landed:'Landed',crashed:'Lost'};$('phase').textContent=n[mode];$('transfer').disabled=mode!=='orbit';$('transfer').textContent=mode==='orbit'?'Start transfer burn':mode==='transfer'?'Transfer in progress':'Reach orbit first'}
function launch(){let s=stats();if(!s.valid||s.cost>save.credits)return;save.credits-=s.cost;persist();Object.assign(ship,{x:0,y:0,vx:0,vy:0,a:0,av:0,th:.72,fuel:s.fuel,maxFuel:s.fuel,hull:100,mass:s.mass,thrust:s.thrust,control:1+s.wing*.24,legs:s.leg,target:null,alt:0});parts=[];mode='launch';showScreen('flight');banner('<b>Launch:</b> hold thrust, then rotate right to build horizontal speed.');log('<b>Liftoff.</b> Vehicle cleared the tower.');phaseUI();hud()}
function transfer(){if(mode!=='orbit')return;let p=WORLDS.find(x=>x.id===world),need=18+p.dist*2.4;if(ship.fuel<need){banner(`<b>Insufficient fuel:</b> ${Math.ceil(need)} units required.`);return}ship.fuel-=need;ship.target=p;progress=0;duration=5+p.dist*.38;mode='transfer';banner(`<b>Transfer:</b> coasting toward ${p.n}.`);log(`Course set for <b>${p.n}</b>.`);phaseUI()}
function descend(){let p=ship.target;mode='landing';Object.assign(ship,{x:0,y:12500,vx:(Math.random()-.5)*18,vy:-44,a:(Math.random()-.5)*.26,av:0,th:0,alt:12500});banner(`<b>${p.n} descent:</b> land upright below ${p.safe} m/s.`);log(`Descent initiated over ${p.n}.`);phaseUI()}
function result(ok,title,text){if(modal)return;modal=true;$('micon').textContent=ok?'🏁':'💥';$('meyebrow').textContent=ok?'Mission accomplished':'Mission failure';$('mtitle').textContent=title;$('mtext').textContent=text;$('modal').classList.add('show')}
function crash(reason){mode='crashed';ship.hull=0;for(let i=0;i<70;i++)parts.push({x:ship.x,y:ship.y,vx:(Math.random()-.5)*170,vy:Math.random()*120-20,life:Math.random()*1.2+.4,max:1.6,r:Math.random()*4+2,col:Math.random()>.5?'#ffb65f':'#ff6379'});result(false,'Vehicle lost',reason+' Return to the shipyard and try a safer design.');phaseUI()}
function landed(){let p=ship.target;mode='landed';ship.th=0;let reward=Math.round(p.reward*(.75+Math.max(0,1-Math.abs(ship.a)/.45)*.45));save.credits+=reward;save.landings++;let i=WORLDS.findIndex(x=>x.id===p.id);if(save.unlock===i+1&&save.unlock<WORLDS.length)save.unlock++;persist();drawWorldUI();result(true,`${p.n} landing complete`,`You landed safely and earned ${fmt(reward)} credits.`);phaseUI()}
function controls(dt,m=1){if(key.left)ship.av-=1.42*ship.control*dt*m;if(key.right)ship.av+=1.42*ship.control*dt*m;ship.av*=Math.pow(.13,dt);ship.a+=ship.av*dt;ship.a=((ship.a+Math.PI)%(Math.PI*2))-Math.PI;if(key.up)ship.th=Math.min(1,ship.th+.68*dt);if(key.down)ship.th=Math.max(0,ship.th-.85*dt)}
function thrust(dt,scale=1){if(ship.fuel<=0||ship.th<=.001)return;let burn=ship.thrust/120*ship.th*dt*scale,use=Math.min(ship.fuel,burn);ship.fuel-=use;let acc=ship.thrust/Math.max(5,ship.mass)*1.1*ship.th*(use/Math.max(.001,burn));ship.vx+=Math.sin(ship.a)*acc*dt;ship.vy+=Math.cos(ship.a)*acc*dt;if(Math.random()<.72)parts.push({x:ship.x-Math.sin(ship.a)*18,y:ship.y-Math.cos(ship.a)*18,vx:ship.vx-Math.sin(ship.a)*(25+Math.random()*30),vy:ship.vy-Math.cos(ship.a)*(25+Math.random()*30),life:Math.random()*.4+.25,max:.65,r:Math.random()*3+2,col:Math.random()>.5?'#67e4ff':'#bd88ff'})}
function moduleDraw(c,k,x,y,z,a=0){let p=P[k];c.save();c.translate(x,y);c.rotate(a);c.fillStyle=p.col;c.strokeStyle='#ffffff88';c.lineWidth=1.1;c.shadowColor=p.col;c.shadowBlur=8;if(k==='pod'){c.beginPath();c.moveTo(0,-z*.48);c.lineTo(z*.38,z*.18);c.lineTo(z*.3,z*.42);c.lineTo(-z*.3,z*.42);c.lineTo(-z*.38,z*.18);c.closePath();c.fill();c.stroke()}else if(k==='tank'){c.beginPath();c.roundRect(-z*.3,-z*.48,z*.6,z*.96,z*.14);c.fill();c.stroke()}else if(k==='engine'){c.beginPath();c.moveTo(-z*.3,-z*.42);c.lineTo(z*.3,-z*.42);c.lineTo(z*.44,z*.42);c.lineTo(-z*.44,z*.42);c.closePath();c.fill();c.stroke()}else if(k==='boost'){c.beginPath();c.roundRect(-z*.25,-z*.48,z*.5,z*.9,z*.12);c.fill();c.stroke()}else if(k==='wing'){c.beginPath();c.moveTo(-z*.35,z*.38);c.lineTo(z*.32,-z*.36);c.lineTo(z*.25,z*.38);c.closePath();c.fill();c.stroke()}else{c.lineWidth=Math.max(3,z*.11);c.lineCap='round';c.beginPath();c.moveTo(-z*.12,-z*.38);c.lineTo(z*.12,z*.28);c.lineTo(z*.35,z*.42);c.stroke()}c.restore()}
function drawBuilder(){let w=buildCanvas.width,h=buildCanvas.height;bctx.clearRect(0,0,w,h);let g=bctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#0e2138');g.addColorStop(1,'#07111e');bctx.fillStyle=g;bctx.fillRect(0,0,w,h);let cell=45,ox=(w-cell*5)/2,oy=28;bctx.strokeStyle='#70dfff20';for(let r=0;r<8;r++)for(let c=0;c<5;c++){let x=ox+c*cell,y=oy+r*cell;bctx.fillStyle='#18304a88';bctx.beginPath();bctx.roundRect(x+3,y+3,cell-6,cell-6,8);bctx.fill();bctx.stroke();if(grid[r][c])moduleDraw(bctx,grid[r][c],x+cell/2,y+cell/2,cell*.72)}}
function buildTap(e){if(mode!=='build')return;let r=buildCanvas.getBoundingClientRect(),sx=buildCanvas.width/r.width,sy=buildCanvas.height/r.height,x=(e.clientX-r.left)*sx,y=(e.clientY-r.top)*sy,cell=45,ox=(buildCanvas.width-cell*5)/2,oy=28,c=Math.floor((x-ox)/cell),row=Math.floor((y-oy)/cell);if(c>=0&&c<5&&row>=0&&row<8){grid[row][c]=grid[row][c]?null:chosen;updateBuild()}}
buildCanvas.addEventListener('pointerdown',buildTap);
function yard(){modal=false;$('modal').classList.remove('show');mode='build';parts=[];showScreen('build');phaseUI();updateBuild()}
$('starter').onclick=starter;$('launch').onclick=launch;$('transfer').onclick=transfer;$('yard').onclick=yard;$('yardTop').onclick=yard;$('retry').onclick=()=>{modal=false;$('modal').classList.remove('show');mode='build';showScreen('build');updateBuild()};
function bindTouch(){document.querySelectorAll('[data-k]').forEach(b=>{let k=b.dataset.k;const on=e=>{e.preventDefault();key[k]=true;if(b.setPointerCapture)try{b.setPointerCapture(e.pointerId)}catch{}};const off=e=>{e.preventDefault();key[k]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('lostpointercapture',off)})}
bindTouch();drawPartsUI();drawWorldUI();starter();saveUI();showScreen('build');log('Shipyard online.');
